# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

language = "javascript"
manifest_version = 2
name = "govuk-fastly"
service_id = "0yW7THGQHtorLIDxhrcWx4"

[scripts]
  build = "npm exec webpack && npm exec js-compute-runtime ./bin/index.js ./bin/main.wasm"

[local_server]
  [local_server.backends]
    [local_server.backends.origin]
      url="http://localhost:3000"
